repos:
  # Ruff (all Python projects)
  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: v0.2.2
    hooks:
      - id: ruff
        name: ruff (update_for_select)
        files: ^update_for_select/
      - id: ruff
        name: ruff (sms_forwarding)
        files: ^sms_forwarding/
      - id: ruff
        name: ruff (sms_relay)
        files: ^sms_relay/

  # isort (all Python projects)
  - repo: https://github.com/PyCQA/isort
    rev: 5.12.0
    hooks:
      - id: isort
        name: isort (update_for_select)
        files: ^update_for_select/
      - id: isort
        name: isort (sms_forwarding)
        files: ^sms_forwarding/
      - id: isort
        name: isort (sms_relay)
        files: ^sms_relay/

  # autoflake8 (all Python projects)
  - repo: https://github.com/fsouza/autoflake8
    rev: v0.3.2
    hooks:
      - id: autoflake8
        name: flake8 (update_for_select)
        files: ^update_for_select/
      - id: autoflake8
        name: flake8 (sms_forwarding)
        files: ^sms_forwarding/
      - id: autoflake8
        name: flake8 (sms_relay)
        files: ^sms_relay/

  # mypy (Python type hint projets)
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.8.0
    hooks:
      - id: mypy
        name: mypy (sms_forwarding)
        files: ^sms_forwarding/
        additional_dependencies: [fastapi, pydantic]
      - id: mypy
        name: mypy (sms_relay)
        files: ^sms_rlay/
        additional_dependencies: [fastapi, pydantic]

