"""update message

Revision ID: 2af4c46cf61c
Revises: 43559796121e
Create Date: 2025-08-23 02:03:44.749122

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '2af4c46cf61c'
down_revision: Union[str, None] = '43559796121e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('forwarded_message', sa.Column('integration_contact_id', sa.UUID(), nullable=True))
    op.add_column('forwarded_message', sa.Column('thread_id', sa.UUID(), nullable=True))
    op.create_index('ix_forwarded_message_thread_date', 'forwarded_message', ['thread_id', 'date'], unique=False)
    op.create_foreign_key(None, 'forwarded_message', 'integration_contact', ['integration_contact_id'], ['id'])
    op.create_foreign_key(None, 'forwarded_message', 'conversation_thread', ['thread_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'forwarded_message', type_='foreignkey')
    op.drop_constraint(None, 'forwarded_message', type_='foreignkey')
    op.drop_index('ix_forwarded_message_thread_date', table_name='forwarded_message')
    op.drop_column('forwarded_message', 'thread_id')
    op.drop_column('forwarded_message', 'integration_contact_id')
    # ### end Alembic commands ###
