"""add rule type to contact rule and create enum

Revision ID: ccb6cc010001
Revises: f3f71504f607
Create Date: 2025-08-17 17:27:04.997466

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'ccb6cc010001'
down_revision: Union[str, None] = 'f3f71504f607'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("CREATE TYPE rule_type_enum AS ENUM ('CONTACT', 'EXTERNAL', 'SYSTEM')")
    op.add_column('contact_rule_type', sa.Column('rule_type', sa.Enum('CONTACT', 'EXTERNAL', 'SYSTEM', name='rule_type_enum'), server_default='CONTACT', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('contact_rule_type', 'rule_type')
    op.execute("DROP TYPE rule_type_enum")
    # ### end Alembic commands ###
