"""enable rule

Revision ID: f3f71504f607
Revises: cc4758ac4932
Create Date: 2025-08-17 02:11:42.472311

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'f3f71504f607'
down_revision: Union[str, None] = 'cc4758ac4932'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contact_rule_config_rules', sa.Column('enabled', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('contact_rule_config_rules', 'enabled')
    # ### end Alembic commands ###
