"""contact must be nullable now

Revision ID: 788fa62fbaac
Revises: 10db307e2c31
Create Date: 2025-08-23 20:58:56.913561

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '788fa62fbaac'
down_revision: Union[str, None] = '10db307e2c31'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('forwarded_message', 'contact_id',
               existing_type=sa.UUID(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('forwarded_message', 'contact_id',
               existing_type=sa.UUID(),
               nullable=False)
    # ### end Alembic commands ###
