"""integration payload schema

Revision ID: 9a4f6638614e
Revises: dc2bd0dd5ee3
Create Date: 2025-08-21 18:53:50.566136

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '9a4f6638614e'
down_revision: Union[str, None] = 'dc2bd0dd5ee3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('integration_webhook_payload',
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('provider', sa.Enum('TELNYX', name='integration_provider'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_integration_webhook_payload_id'), 'integration_webhook_payload', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_integration_webhook_payload_id'), table_name='integration_webhook_payload')
    op.drop_table('integration_webhook_payload')
    # ### end Alembic commands ###
