"""integration fk

Revision ID: 8fe6e0c03175
Revises: 9a4f6638614e
Create Date: 2025-08-22 00:46:06.654611

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '8fe6e0c03175'
down_revision: Union[str, None] = '9a4f6638614e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('forwarded_message', sa.Column('integration_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'forwarded_message', 'integration_webhook_payload', ['integration_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'forwarded_message', type_='foreignkey')
    op.drop_column('forwarded_message', 'integration_id')
    # ### end Alembic commands ###
