"""contactrule

Revision ID: 4b7102714be2
Revises: ed37a2345547
Create Date: 2025-08-16 01:32:25.665862

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '4b7102714be2'
down_revision: Union[str, None] = 'ed37a2345547'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rule_type',
    sa.Column('category', sa.Enum('ENABLED', 'ALWAYS_FORWARD', 'AUTODELETE', 'BUSINESS_HOURS_FORWARD', 'DISPLAY', name='contact_rule_categories'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rule_type_id'), 'rule_type', ['id'], unique=False)
    op.create_table('contact_rule_config_rules',
    sa.Column('config_id', sa.UUID(), nullable=False),
    sa.Column('rule_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['config_id'], ['contact_rule_config.id'], ),
    sa.ForeignKeyConstraint(['rule_id'], ['rule_type.id'], ),
    sa.PrimaryKeyConstraint('config_id', 'rule_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('contact_rule_config_rules')
    op.drop_index(op.f('ix_rule_type_id'), table_name='rule_type')
    op.drop_table('rule_type')
    # ### end Alembic commands ###
