"""integration contact

Revision ID: 4e928d47fa49
Revises: 8fe6e0c03175
Create Date: 2025-08-23 01:45:58.148028

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '4e928d47fa49'
down_revision: Union[str, None] = '8fe6e0c03175'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('integration_contact',
    sa.Column('address', sa.String(length=255), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_integration_contact_id'), 'integration_contact', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_integration_contact_id'), table_name='integration_contact')
    op.drop_table('integration_contact')
    # ### end Alembic commands ###
