"""conversation

Revision ID: 43559796121e
Revises: 4e928d47fa49
Create Date: 2025-08-23 02:01:57.481811

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '43559796121e'
down_revision: Union[str, None] = '4e928d47fa49'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('conversation_thread',
    sa.Column('contact_id', sa.UUID(), nullable=False),
    sa.Column('integration_contact_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['contact_id'], ['contact.id'], ),
    sa.ForeignKeyConstraint(['integration_contact_id'], ['integration_contact.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_conversation_thread_contact', 'conversation_thread', ['contact_id'], unique=False)
    op.create_index(op.f('ix_conversation_thread_created'), 'conversation_thread', ['created'], unique=False)
    op.create_index(op.f('ix_conversation_thread_id'), 'conversation_thread', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_conversation_thread_id'), table_name='conversation_thread')
    op.drop_index(op.f('ix_conversation_thread_created'), table_name='conversation_thread')
    op.drop_index('ix_conversation_thread_contact', table_name='conversation_thread')
    op.drop_table('conversation_thread')
    # ### end Alembic commands ###
