"""save a join

Revision ID: 10db307e2c31
Revises: 87c2e1d82c97
Create Date: 2025-08-23 20:48:19.566995

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '10db307e2c31'
down_revision: Union[str, None] = '87c2e1d82c97'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('conversation_thread', sa.Column('phone_number_used', sa.String(length=15), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('conversation_thread', 'phone_number_used')
    # ### end Alembic commands ###
