"""more message changes

Revision ID: 87c2e1d82c97
Revises: 7259405f144d
Create Date: 2025-08-23 19:22:08.128731

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '87c2e1d82c97'
down_revision: Union[str, None] = '7259405f144d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('forwarded_message', sa.Column('device', sa.Boolean(), nullable=False))
    op.add_column('forwarded_message', sa.Column('delivery_confirmed', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_forwarded_message_delivery_confirmed'), 'forwarded_message', ['delivery_confirmed'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_forwarded_message_delivery_confirmed'), table_name='forwarded_message')
    op.drop_column('forwarded_message', 'delivery_confirmed')
    op.drop_column('forwarded_message', 'device')
    # ### end Alembic commands ###
