"""relayed column on message

Revision ID: dc2bd0dd5ee3
Revises: ccb6cc010001
Create Date: 2025-08-21 18:48:38.330375

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'dc2bd0dd5ee3'
down_revision: Union[str, None] = 'ccb6cc010001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('forwarded_message', sa.Column('relayed', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('forwarded_message', 'relayed')
    # ### end Alembic commands ###
