"""forgotten column

Revision ID: 7259405f144d
Revises: 2af4c46cf61c
Create Date: 2025-08-23 02:04:11.521858

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '7259405f144d'
down_revision: Union[str, None] = '2af4c46cf61c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('integration_contact', sa.Column('provider', sa.Enum('TELNYX', name='integration_provider'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('integration_contact', 'provider')
    # ### end Alembic commands ###
